/**
 * AI Asset Generator — hero / banner / thumbnail images.
 *
 * OWNER: feat/asset-generator (Wave 2). This stub fixes the public surface so
 * routes compile before the feature lands. Keys are read at call time, never
 * at import; generated bytes go through `@plink/storage`, never straight to a
 * URL the model invented.
 */

export const ASSET_KINDS = ["hero", "banner", "thumbnail"] as const;
export type AssetKind = (typeof ASSET_KINDS)[number];

export type GenerateAssetInput = {
  kind: AssetKind;
  /** Operator prompt, clamped by the implementation. */
  prompt: string;
};

export type GeneratedAsset = {
  /** Blob URL after upload through @plink/storage. */
  url: string;
  mimeType: string;
};

/**
 * Generates one image via the AI Gateway and stores it.
 * Implemented by feat/asset-generator; until then callers must gate on
 * `aiEnabled()` and treat this as unavailable.
 */
export async function generateAssetImage(_input: GenerateAssetInput): Promise<GeneratedAsset> {
  throw new Error("Asset generation is not implemented yet (feat/asset-generator).");
}
